BEGIN TRANSACTION;
INSERT INTO users (username,password_hash,role) VALUES ('user','$2a$08$UkVvwpULis18S19S5pZFn.YHPZt3oaqHZnDwqbCW9pft6uFtkXKDC','ROLE_USER');
INSERT INTO users (username,password_hash,role) VALUES ('admin','$2a$08$UkVvwpULis18S19S5pZFn.YHPZt3oaqHZnDwqbCW9pft6uFtkXKDC','ROLE_ADMIN');
INSERT INTO users (username,password_hash,role) VALUES ('ace','$2a$08$UkVvwpULis18S19S5pZFn.YHPZt3oaqHZnDwqbCW9pft6uFtkXKDC','ROLE_USER');
INSERT INTO custom_recipes (name, ingredients, instructions, image)
VALUES ('Chicken Parmesan', 'Two large chicken breasts, One cup breadcrumbs, One cup grated Parmesan cheese, One egg, Salt, Pepper, Olive oil, One cup marinara sauce, Half cup shredded mozzarella cheese, Fresh basil leaves', 'Preheat your oven to 400°F. Pound the chicken breasts until they are about half an inch thick. In a shallow dish, mix together the breadcrumbs and grated Parmesan cheese. In another dish, beat the egg. Season the chicken breasts with salt and pepper. Dip each chicken breast in the beaten egg, then coat with the breadcrumb mixture. Heat olive oil in a skillet over medium heat. Cook the chicken breasts for about 3 minutes on each side until golden brown. Transfer the chicken breasts to a baking dish. Top each chicken breast with marinara sauce and shredded mozzarella cheese. Bake in the preheated oven for 15-20 minutes or until the cheese is melted and bubbly. Garnish with fresh basil leaves before serving stir-fry over cooked rice stir-fry over cooked.', 'https://www.skinnytaste.com/wp-content/uploads/2012/09/skinny-chicken-parmigiana-550x733.jpg');
INSERT INTO custom_recipes (name, ingredients, instructions, image)
VALUES ('Beef Stir Fry', 'One pound beef sirloin, Three tablespoons soy sauce, Two tablespoons hoisin sauce, One tablespoon oyster sauce, One tablespoon cornstarch, One tablespoon sesame oil, One tablespoon vegetable oil, Two cloves garlic, minced, One inch fresh ginger, grated, One onion, sliced, Two bell peppers, sliced, One cup broccoli florets, Cooked rice, for serving', 'Slice the beef sirloin thinly against the grain. In a bowl, mix together soy sauce, hoisin sauce, oyster sauce, and cornstarch. Add the sliced beef to the sauce mixture and marinate for 15-30 minutes. Heat sesame oil and vegetable oil in a wok or skillet over high heat. Add minced garlic and grated ginger to the hot oil and stir-fry for about 30 seconds. Add sliced onion, bell peppers, and broccoli florets to the wok and stir-fry for 2-3 minutes until slightly tender.  Return the cooked vegetables to the wok and toss with the beef. Serve the beef stir-fry over cooked rice.', 'https://www.saltandlavender.com/wp-content/uploads/2022/12/beef-stir-fry-1.jpg');
INSERT INTO custom_recipes (name, ingredients, instructions, image)
VALUES ('Lasagna', 'One box lasagna noodles, One jar marinara sauce, Two cups ricotta cheese, One cup grated Parmesan cheese, One egg, Two cups shredded mozzarella cheese, One zucchini, sliced, One yellow squash, sliced, One bell pepper, sliced, One onion, sliced, Two cloves garlic, minced, Olive oil, Salt, Pepper, Fresh basil leaves', 'Preheat your oven to 375°F. Cook the lasagna noodles according to the package instructions. In a bowl, mix together ricotta cheese, grated Parmesan cheese, and beaten egg. In a skillet, heat olive oil over medium heat. Add minced garlic and sliced onion to the skillet and cook until softened. Add sliced zucchini, yellow squash, and bell pepper to the skillet and cook until tender. Season with salt and pepper. Spread a thin layer of marinara sauce on the bottom of a baking dish. Arrange a layer of cooked lasagna noodles on top of the sauce. Spread a layer of the ricotta cheese mixture over the nh.', 'https://www.modernhoney.com/wp-content/uploads/2019/08/Classic-Lasagna-14-scaled.jpg');
INSERT INTO custom_recipes (name, ingredients, instructions, image)
VALUES ('Sambusa', 'One pound beef sirloin, Three tablespoons soy sauce, Two tablespoons hoisin sauce, One tablespoon oyster sauce, One tablespoon cornstarch, One tablespoon sesame oil, One tablespoon vegetable oil, Two cloves garlic, minced, One inch fresh ginger, grated, One onion, sliced, Two bell peppers, sliced, One cup broccoli florets, Cooked rice, for serving', 'Slice the beef sirloin thinly against the grain. In a bowl, mix together soy sauce, hoisin sauce, oyster sauce, and cornstarch. Add the sliced beef to the sauce mixture and marinate for 15-30 minutes. Heat sesame oil and vegetable oil in a wok or skillet over high heat. Add minced garlic and grated ginger to the hot oil and stir-fry for about 30 seconds. Add sliced onion, bell peppers, and broccoli florets to the wok and stir-fry for 2-3 minutes until slightly tender.  Return the cooked vegetables to the wok and toss with the beef. Serve the beef stir-fry over cooked rice.', 'https://gimmedelicious.com/wp-content/uploads/2024/03/Sambusa-6-500x500.jpg');
INSERT INTO user_custom_recipes(user_id, custom_recipe_id)
VALUES (3, 1);
INSERT INTO user_custom_recipes(user_id, custom_recipe_id)
VALUES (3, 2);
INSERT INTO user_custom_recipes(user_id, custom_recipe_id)
VALUES (3, 3);
INSERT INTO user_custom_recipes(user_id, custom_recipe_id)
VALUES (3, 4);
COMMIT TRANSACTION;